<?php


namespace app\exception;
use think\Exception;
use think\exception\Handle;

class ExceptionHandle extends Handle
{
    public function render(\Exception $ex)
    {
        return json($ex);
//        return parent::render($e); // TODO: Change the autogenerated stub
    }
}